use std::{collections::{HashMap, HashSet}, time::Instant};

use itertools::Itertools;
use petgraph::visit::EdgeRef;

use crate::{
    analysis::graph::{get_program_cfg, Edge, Node},
    intermediate_representation::{Def, Expression, Project, Variable},
    prelude::{Term, Tid},
    utils::debug::IrForm,
};

use super::{
    prelude::{LogMessage, Program},
    IrPass,
};

pub const SPLIT_SYMBOL: &str = "__";

/// Computes register-SSA with a really crude approach
/// For each register used in the program, we add a phi instruction at the start of each block.
/// Will also replace temp variables generated by ghidra. Currently assuming that every temp
/// variable is only used within the original isntruction, so not crossing block boundaries.
/// This is not memory efficent. However, it is easy to restore SSA after adding an edge to the SSA:
/// Add the new varaibles to the phi functions of the receiving block.
///
/// ## SSA:
/// Every variable gets assigned once statically.
/// phi functions can join variables: new_var = phi(...)
/// phi: Var X ... X Var -> Var
///
/// ## How does it work?
/// - Add to every block phi functions for every register and rename all vars
/// - Get all incoming edges to the block
/// - Add at the start of the blocks each possible incoming edge to the phi functions
///
/// Supports: interprocedure calls, and interprocedure jumps (call/return). Might not support external calls
/// correctly.

pub type VarsAtEndOfBlock = HashMap<Tid, Vec<Variable>>;

pub struct SingleStaticAssigment {
    register_vars: Vec<Variable>,
    pub active_var_at_end_of_block: VarsAtEndOfBlock,
}

impl SingleStaticAssigment {
    fn get_used_register(&self, program: &Program) -> Vec<Variable> {
        // We need to aggregate all names, as we do the really crude method!
        let mut var_names = HashSet::new();
        for sub in &program.subs {
            for blks in sub.1.blocks() {
                for defs in blks.defs() {
                    match &defs.term {
                        Def::Load { var, .. } | Def::Assign { var, .. } => {
                            var_names.insert(var.clone())
                        }
                        Def::Store { .. } => false,
                    };
                }
            }
        }

        //let mut used_register_vars = Vec::new();

        //for register_var in &self.register_vars {
        //    // TODO: all temp variables are now used
        //    if var_names.contains(&register_var.name) || true {
        //        used_register_vars.push(register_var.clone());
        //    }
        //}

        //used_register_vars
        var_names.iter().map(|v| v.clone()).collect_vec()
    }
}

fn get_incoming_edges_for_each_blk(program: &Program) -> HashMap<String, HashSet<String>> {
    let mut cfg = get_program_cfg(program);
    cfg.reverse();
    let cfg_unreversed = get_program_cfg(program);
    // Saves the incoming edges for each block
    let mut incoming_edge_for_each_block = HashMap::<String, HashSet<String>>::new();
    for block in program.blocks() {
        incoming_edge_for_each_block.insert(block.tid.to_string(), HashSet::<String>::new());
    }

    for node in cfg.node_indices() {
        match cfg[node] {
            Node::BlkStart(_, _) => {
                let edges = cfg.edges(node);
                for edge in edges {
                    let target_node = edge.target();
                    if let Some(blk) = cfg[target_node].try_get_block() {
                        let incoming_edges = incoming_edge_for_each_block
                            .get_mut(&cfg[edge.source()].get_block().tid.to_string())
                            .expect("Blk had no key in incoming_edge_for_each_block, should never happen");
                        incoming_edges.insert(blk.tid.to_string());
                    }
                }
            }
            Node::CallSource { source, target } => {
                let source = source.0.tid.clone();
                let target = target.0.tid.clone();
                let incoming_edges = incoming_edge_for_each_block
                    .get_mut(&target.to_string())
                    .expect("Blk had no key in incoming_edge_for_each_block, should never happen");
                incoming_edges.insert(source.to_string());
            }
            Node::CallReturn { return_, .. } => {
                for edge in cfg_unreversed.edges(node) {
                    if let Edge::ReturnCombine(_) = edge.weight() {
                        let source = return_.0.tid.clone();
                        let target = cfg[edge.target()].get_block().tid.to_string();
                        let incoming_edges = incoming_edge_for_each_block
                            .get_mut(&target.to_string())
                            .expect("Blk had no key in incoming_edge_for_each_block, should never happen");
                        incoming_edges.insert(source.to_string());
                    }
                }
            }
            _ => (),
        }
    }

    incoming_edge_for_each_block
}

impl SingleStaticAssigment {
    fn rename_all_vars_and_add_empty_phi_fn(
        &mut self,
        program: &mut Program,
        used_register_vars: &Vec<Variable>,
    ) -> HashMap<String, HashMap<String, i64>> {
        // hashMap: [block_name][var_name] = curr_index
        let mut active_var_at_end_of_block = HashMap::<String, HashMap<String, i64>>::new();
        let mut active_indices = HashMap::<String, i64>::new();
        for var in used_register_vars {
            active_indices.insert(var.name.clone(), 0);
        }
        for block in program.blocks_mut() {
            let mut phi_instruction_at_begin = used_register_vars
                .iter()
                .map(|var| {
                    let new_var_index = active_indices[&var.name] + 1;
                    active_indices.insert(var.name.clone(), new_var_index);
                    Term {
                        tid: Tid::new_phi(&block.tid, &var.name),
                        term: Def::Assign {
                            var: Variable {
                                name: format!("{}{}{}", &var.name, SPLIT_SYMBOL, new_var_index),
                                size: var.size,
                                is_temp: var.is_temp,
                            },
                            // TODO fill in
                            value: Expression::Phi(vec![]),
                        },
                    }
                })
                .collect_vec();
            phi_instruction_at_begin.extend(block.defs.clone());
            block.defs = phi_instruction_at_begin;

            for def in &mut block.defs {
                for var in used_register_vars {
                    def.substitute_input_var(
                        &var,
                        &Expression::Var(Variable {
                            name: format!(
                                "{}{}{}",
                                var.name, SPLIT_SYMBOL, active_indices[&var.name]
                            ),
                            size: var.size,
                            is_temp: var.is_temp,
                        }),
                    )
                }
                match &mut def.term {
                    Def::Assign { var, .. } | Def::Load { var, .. } => {
                        if used_register_vars.contains(var) {
                            let new_var_index = active_indices[&var.name] + 1;
                            active_indices.insert(var.name.clone(), new_var_index);
                            var.name =
                                format!("{}{}{}", var.name, SPLIT_SYMBOL, new_var_index).to_owned();
                        }
                    }
                    _ => (),
                }
            }

            for jmp in &mut block.jmps_mut() {
                for var in used_register_vars {
                    jmp.term.substitute_input_var(
                        &var,
                        &Expression::Var(Variable {
                            name: format!(
                                "{}{}{}",
                                var.name, SPLIT_SYMBOL, active_indices[&var.name]
                            ),
                            size: var.size,
                            is_temp: var.is_temp,
                        }),
                    )
                }
            }

            let mut active_vars = vec![];
            for var in used_register_vars {
                active_vars.push(Variable {
                    name: format!("{}{}{}", var.name, SPLIT_SYMBOL, active_indices[&var.name]),
                    size: var.size,
                    is_temp: var.is_temp,
                });
            }

            active_var_at_end_of_block.insert(block.tid.to_string(), active_indices.clone());
            self.active_var_at_end_of_block
                .insert(block.tid.clone(), active_vars.clone());
        }
        active_var_at_end_of_block
    }
}

/// Renames all temp variables. temp varaibles are only used within one instruction but the name is
/// reused.*
///
/// * this is at moment a hypothesis.
fn rename_temp_variables(program: &mut Program) {
    let mut active_indices = HashMap::<Variable, i64>::new();

    for block in program.blocks_mut() {
        for def in &mut block.defs {
            for (var, index) in &active_indices {
                def.substitute_input_var(
                    &var,
                    &Expression::Var(Variable {
                        name: format!("{}{}{}", var.name, SPLIT_SYMBOL, active_indices[&var]),
                        size: var.size,
                        is_temp: true,
                    }),
                )
            }
            match &mut def.term {
                Def::Assign { var, .. } | Def::Load { var, .. } => {
                    if var.is_temp {
                        let new_var_index = active_indices.get(&var).unwrap_or(&0_i64) + 1;
                        active_indices.insert(var.clone(), new_var_index);
                        var.name =
                            format!("{}{}{}", var.name, SPLIT_SYMBOL, new_var_index).to_owned();
                    }
                }
                _ => (),
            }
        }

        for jmp in &mut block.jmps_mut() {
            for (var, index) in &active_indices {
                jmp.term.substitute_input_var(
                    &var,
                    &Expression::Var(Variable {
                        name: format!("{}{}{}", var.name, SPLIT_SYMBOL, index),
                        size: var.size,
                        is_temp: var.is_temp,
                    }),
                )
            }
        }
    }
    println!("Temp vars {}", active_indices.len());
}

fn fix_phi_functions(
    program: &mut Program,
    incoming_edge_for_each_block: HashMap<String, HashSet<String>>,
    active_var_at_end_of_block: HashMap<String, HashMap<String, i64>>,
) {
    for block in program.blocks_mut() {
        for incoming_edge_name in &incoming_edge_for_each_block[&block.tid.to_string()] {
            for def in block.defs_mut() {
                if let Term {
                    term:
                        Def::Assign {
                            var,
                            value: Expression::Phi(inputs),
                        },
                    ..
                } = def
                {
                    let original_name = var.name.split(SPLIT_SYMBOL).take(1).collect_vec()[0];
                    inputs.push(Variable {
                        name: format!(
                            "{}{}{}",
                            original_name,
                            SPLIT_SYMBOL,
                            active_var_at_end_of_block[&incoming_edge_name.clone()][original_name]
                        ),
                        size: var.size,
                        is_temp: var.is_temp,
                    })
                }
            }
        }
    }
}

impl IrPass for SingleStaticAssigment {
    const NAME: &'static str = "SingleStaticAssigment";

    const DBG_IR_FORM: super::prelude::debug::IrForm = IrForm::SingleStaticAssigment;

    type Input = Program;
    type ConstructionInput = Project;

    fn new(construction_input: &Self::ConstructionInput) -> Self {
        return SingleStaticAssigment {
            register_vars: construction_input
                .register_set
                .iter()
                .map(|var| var.clone())
                .clone()
                .collect_vec(),
            active_var_at_end_of_block: VarsAtEndOfBlock::new(),
        };
    }

    fn run(&mut self, mut program: &mut Self::Input) -> Vec<super::prelude::LogMessage> {
        let mut logs: Vec<LogMessage> = vec![];

        let mut last_time = Instant::now();
        eprintln!("Starting SSA Transform");
        eprintln!("Collecting used_register_vars: {:02?}", last_time.elapsed());
        last_time = Instant::now();

        let used_register_vars = self.get_used_register(&program);

        logs.push(LogMessage::new_info(format!(
            "Found following var names {}",
            itertools::join(&used_register_vars, ",")
        )));
        eprintln!("Incoming edge for each bloc: {:02?}", last_time.elapsed());
        last_time = Instant::now();

        let incoming_edge_for_each_block = get_incoming_edges_for_each_blk(&program);
        eprintln!("Active Var at the end of block: {:02?}", last_time.elapsed());
        last_time = Instant::now();

        let active_var_at_end_of_block =
            self.rename_all_vars_and_add_empty_phi_fn(&mut program, &used_register_vars);
        eprintln!("Fix PHI Functions: {:02?}", last_time.elapsed());
        last_time = Instant::now();

        fix_phi_functions(
            program,
            incoming_edge_for_each_block,
            active_var_at_end_of_block,
        );
        eprintln!("Done SSA: {:02?}", last_time.elapsed());
        //rename_temp_variables(program);

        logs
    }

    fn assert_postconditions(
        _construction_input: &Self::ConstructionInput,
        _program: &Self::Input,
    ) {
        todo!()
    }
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use itertools::Itertools;
    use project::{SingleStaticAssigment, SPLIT_SYMBOL};

    use crate::expr;
    use crate::ghidra_pcode::ir_passes::IrPass;
    use crate::{defs, intermediate_representation::*, run_ir_pass, utils::debug};

    #[test]
    fn test_calls_ssa() {
        // took from mock_program
        let call_term = Term {
            tid: Tid::new("call".to_string()),
            term: Jmp::Call {
                target: Tid::new("sub2"),
                return_: Some(Tid::new("sub1_blk2")),
            },
        };
        let return_term = Term {
            tid: Tid::new("return".to_string()),
            term: Jmp::Return(expr!("0:8")), // The return term does not matter
        };
        let jmp = Jmp::Branch(Tid::new("sub1_blk1"));
        let jmp_term = Term {
            tid: Tid::new("jump"),
            term: jmp,
        };
        let mut blk = Blk::default();
        blk.defs = defs!["term1: RAX:8 = 0x1:8"];
        blk.add_jumps(vec![call_term]);
        let sub1_blk1 = Term {
            tid: Tid::new("sub1_blk1"),
            term: blk,
        };
        let mut blk = Blk::default();
        blk.add_jumps(vec![jmp_term]);
        let sub1_blk2 = Term {
            tid: Tid::new("sub1_blk2"),
            term: blk,
        };
        let sub1 = Term {
            tid: Tid::new("sub1"),
            term: Sub::new::<_, &str>("sub1", vec![sub1_blk1, sub1_blk2], None),
        };
        let cond_jump = Jmp::CBranch {
            target: Tid::new("sub1_blk1"),
            condition: expr!("0:1"),
        };
        let cond_jump_term = Term {
            tid: Tid::new("cond_jump"),
            term: cond_jump,
        };
        let jump_term_2 = Term {
            tid: Tid::new("jump2"),
            term: Jmp::Branch(Tid::new("sub2_blk2")),
        };
        let mut blk = Blk::default();
        blk.add_jumps(vec![cond_jump_term, jump_term_2]);
        let sub2_blk1 = Term {
            tid: Tid::new("sub2_blk1"),
            term: blk,
        };
        let mut blk = Blk::default();
        blk.add_jumps(vec![return_term]);
        let sub2_blk2 = Term {
            tid: Tid::new("sub2_blk2"),
            term: blk,
        };
        let sub2 = Term {
            tid: Tid::new("sub2"),
            term: Sub::new::<_, &str>("sub2", vec![sub2_blk1, sub2_blk2], None),
        };
        let program = Term {
            tid: Tid::new("program"),
            term: Program {
                subs: BTreeMap::from_iter([(sub1.tid.clone(), sub1), (sub2.tid.clone(), sub2)]),
                extern_symbols: BTreeMap::new(),
                entry_points: BTreeSet::new(),
                address_base_offset: 0,
            },
        };

        let mut project = Project::mock_x64();
        project.program = program;

        for blk in project.program.blocks() {
            println!("{}", blk);
        }
        println!("====POST====");
        let mut logs = vec![];
        run_ir_pass![
            project.program,
            project,
            SingleStaticAssigment,
            logs,
            debug::Settings::default()
        ];
        for blk in project.program.blocks() {
            println!("{}", blk);
        }

        assert_phi_function_content(
            "phi_sub1_blk1_RAX",
            &project.program.term,
            format!("RAX{}4,RAX{}3", SPLIT_SYMBOL, SPLIT_SYMBOL).to_string(),
        );
        assert_phi_function_content(
            "phi_sub1_blk2_RAX",
            &project.program.term,
            format!("RAX{}5", SPLIT_SYMBOL).to_string(),
        );
        assert_phi_function_content(
            "phi_sub2_blk1_RAX",
            &project.program.term,
            format!("RAX{}2", SPLIT_SYMBOL).to_string(),
        );
        assert_phi_function_content(
            "phi_sub2_blk2_RAX",
            &project.program.term,
            format!("RAX{}4", SPLIT_SYMBOL).to_string(),
        );
    }

    fn assert_phi_function_content(phi_tid: &str, program: &Program, has_inputs: String) {
        let has_inputs = has_inputs.split(",").collect_vec();
        for blk in program.blocks() {
            for def in blk.defs() {
                if let Term {
                    term:
                        Def::Assign {
                            value: Expression::Phi(inputs),
                            ..
                        },
                    tid,
                } = def
                {
                    if phi_tid != tid.to_string() {
                        continue;
                    }
                    let mut has_inputs = has_inputs.clone();
                    has_inputs.sort();
                    let inputs = inputs.iter().map(|v| v.name.clone()).sorted().collect_vec();
                    assert!(
                        inputs.iter().zip(&has_inputs).all(|(a, b)| a == b),
                        "Missing input in Phi function {}",
                        phi_tid
                    );
                    return;
                }
            }
        }
        assert!(false, "phi_tid {} did not exist", phi_tid);
    }

    /// we built this code:
    /// x = 1; // blk1
    /// y = 2;
    /// if (x > 1) { // blk2
    ///     x = y;
    /// }
    /// y = 1 // blk3
    #[test]
    fn test_ssa() {
        let mut project = Project::mock_x64();
        let mut blk1 = Blk::default();
        blk1.defs = defs!["tid_1: RAX:8 = 0x1:1", "tid_2: RCX:8 = 0x2:1"];
        let mut blk1 = Term {
            tid: Tid::new("blk_1"),
            term: blk1,
        };

        let mut blk2 = Blk::default();
        blk2.defs = defs!["tid_3: RAX:8 = RCX:8"];

        let mut blk3 = Blk::default();
        blk3.defs = defs!["tid_4: RCX:8 = 0x1:1"];
        let blk3 = Term {
            tid: Tid::new("blk_3"),
            term: blk3,
        };

        let if_jmp = Jmp::CBranch {
            target: Tid::new("blk_2").clone(),
            condition: expr!("RAX:8 - 0x1:1"),
        };
        let if_jmp = Term {
            tid: Tid::new("foo_jmp_if"),
            term: if_jmp,
        };
        let else_jmp = Jmp::Branch(Tid::new(blk3.tid.clone()));
        let else_jmp = Term {
            tid: Tid::new("foo_jmp_else"),
            term: else_jmp,
        };
        blk1.term.add_jumps(vec![if_jmp, else_jmp]);
        let jmp_to_3 = Jmp::Branch(Tid::new(blk3.tid.clone()));
        let blk1_jmp = Term {
            tid: Tid::new("foo_jmp_else_2"),
            term: jmp_to_3,
        };
        blk2.add_jumps(vec![blk1_jmp]);
        let blk2 = Term {
            tid: Tid::new("blk_2"),
            term: blk2,
        };

        let mut sub = Sub::mock("main");
        sub.term.blocks.push(blk1);
        sub.term.blocks.push(blk2);
        sub.term.blocks.push(blk3);
        project.program.subs.insert(sub.tid.clone(), sub);

        for blk in project.program.blocks() {
            println!("{}", blk);
        }
        println!("====POST====");
        let mut logs = vec![];
        run_ir_pass![
            project.program,
            project,
            SingleStaticAssigment,
            logs,
            debug::Settings::default()
        ];
        assert_phi_function_content("phi_blk_1_RAX", &project.program.term, "".to_string());
        assert_phi_function_content("phi_blk_1_RCX", &project.program.term, "".to_string());
        assert_phi_function_content(
            "phi_blk_2_RAX",
            &project.program.term,
            format!("RAX{}2", SPLIT_SYMBOL).to_string(),
        );
        assert_phi_function_content(
            "phi_blk_2_RCX",
            &project.program.term,
            format!("RCX{}2", SPLIT_SYMBOL).to_string(),
        );
        assert_phi_function_content(
            "phi_blk_3_RAX",
            &project.program.term,
            format!("RAX{}2,RAX{}4", SPLIT_SYMBOL, SPLIT_SYMBOL).to_string(),
        );
        assert_phi_function_content(
            "phi_blk_3_RCX",
            &project.program.term,
            format!("RCX{}2,RCX{}3", SPLIT_SYMBOL, SPLIT_SYMBOL).to_string(),
        );
    }
}
